@startuml

node "Web-Client" as WebClient {
    [Browser (Nutzer)]
}

node "GoalFinder Hub (Raspberry Pi)" as GoalfinderHub {
    [Webanwendung]
    [Express.js]
}

node "GoalFinder Gerät" as GoalfinderDevice {
    [Sensoren]
}

database "Datenbank (SQL)" as Database {
    [Konfigurationsdaten]
    [Spielstände]
    [Nutzerinformationen]
    [Ranglisteninformation]
}

WebClient --> GoalfinderHub : HTTP (REST API)
GoalfinderDevice --> GoalfinderHub : REST API
GoalfinderHub --> Database : SQLite

@enduml

