@startuml UCD
left to right direction

rectangle GoalFinderHub_Webapp {
    package "Geräteverwaltung" {
        (Übersicht der GoalFinder)
        (Hinzufügen eines GoalFinders)
        (Löschen eines GoalFinders)
        (Einstellungen eines Goalfinders ändern)
        (Software Update)
    }
    package "Spielverwaltung" {
        (Spielmodus einstellen)
        (Teams zuweisen)
        (Match starten)
    }
    package "Teamsverwaltung" {
        (Teams erstellen)
        (Spieler zuweisen)
    }
    package "Historie" {
        (Rangliste einsehen)
        (Rangliste bearbeiten)
    }
}

:Admin: --> (Übersicht der GoalFinder)
:Admin: --> (Hinzufügen eines GoalFinders)
:Admin: --> (Löschen eines GoalFinders)
:Admin: --> (Einstellungen eines Goalfinders ändern)
:Admin: --> (Software Update)

:User: --> (Spielmodus einstellen)
:User: --> (Teams erstellen)
:User: --> (Teams zuweisen)
:User: --> (Match starten)
:User: --> (Rangliste einsehen)
:User: --> (Rangliste bearbeiten)


(Teams erstellen) .> (Spieler zuweisen) : <<include>>
@enduml
