 @startuml Minecraft
skinparam linetype ortho

entity Slot {
    *slot_id
}

entity Inventory {
    *inventory_id
    --
    *size
}

entity Item {
    *item_id
    --
    *name
    *numberOfItems
}

entity Enchantment {
    *enchantment_id
    --
    *name
    *tier
}

entity Player {
    *id
    --
    *name
    *baseHealth
    *currHealth
}

entity Mob {
    *mob_id
    --
    *name
    *baseHealth
    *currHealth
}

entity Effect {
    *effect_id
    --
    *name
    *duration
}

Slot |o--o| Item
Inventory ||--|{ Slot
Mob ||--o| Inventory
Player ||--|| Inventory
Item }o--o{ Enchantment
Player }o--o{ Effect
Mob }o--o{ Effect