POST http://localhost:3000/api/teams
Content-Type: application/json

{
  "name": "Jaja",
  "players": [
    "Alex Coroi" ,
    "Filip"
  ]
}

###
PUT http://localhost:3000/api/teams/3
Content-Type: application/json

{
    "name": "Benji Stoic"
}


###
GET http://localhost:3000/api/teams

###
GET http://localhost:3000/api/teams/3

###
DELETE http://localhost:3000/api/teams/1

###
DELETE http://localhost:3000/api/teams/3/8

###
PUT http://localhost:3000/api/teams/3/Delta

###
GET http://localhost:3000/api/leaderboard

###
GET http://localhost:3000/api/games

###
POST http://localhost:3000/api/games
Content-Type: application/json

{
  "date": "2025-05-21T12:00:00.000Z",
  "homeTeamScore": 5,
  "awayTeamScore": 2,
  "homeTeam": {
    "id": 4,
    "name": "Yellow Yetis"
  },
  "awayTeam": {
    "id": 7,
    "name": "Silver Sharks"
  }
}

###
GET http://localhost:3000/api/settings