services:
  backend:
    restart: always
    build: ./backend
    hostname: backend
    network_mode: "host"
    ports:
      - '3000:3000'
  frontend:
    restart: always
    build: ./frontend
    hostname: frontend
    ports:
      - '80:80'
